pipeline {
    agent {
        docker {
            image 'ubuntu:latest'  // Use the latest Ubuntu image
            args '-u root'         // Run as root
        }
    }
    stages {
        stage('Clone Repository') {
            steps {
                script {
                    // Install Git
                    sh 'apt-get update && apt-get install -y git'
                    // Clone the repository (replace <repo_url> with your repository URL)
                    //sh 'git clone https://github.com/siddarthborigam/Jenkins-Zero-To-Hero.git'
               
                }
            }
        }

        stage('install Java') {
            steps {
                script {
                    // Install Java
                    sh 'apt-get install -y python'
                    sh 'python -version'
                    sh 'ls'
                    //sh 'cd multi-stage-multi-agent'
                    //sh 'java hello_world.java'
                    //sh 'javac hello_world.java'
                    //sh 'java hello_world'
                    
                    
                }
            }
        }
    }
}
