
pipeline {
    agent {
        docker {
            // Use a Java Docker image, e.g., OpenJDK
            image 'openjdk:11-jdk-slim'
            args '-v /var/run/docker.sock:/var/run/docker.sock' // Optional: Mount Docker socket if needed
        }
    }
    stages {
        stage('Checkout') {
            steps {
                // Checkout the repository (assumes you are using Git or similar)
                //checkout scm
                sh 'git clone https://github.com/siddarthborigam/Jenkins-Zero-To-Hero.git'
            }
        }
        stage('Build Java App') {
            steps {
                script {
                    // Compile the Java application
                    sh 'cd multi-stage-multi-agent'
                    sh 'javac hello_world.java'
                }
            }
        }
        stage('Run Java App') {
            steps {
                script {
                    // Run the Java application
                    sh 'java hello_world'
                }
            }
        }
    }
}
