pipeline {
    agent {
        docker {
            //image 'docker:20.10.7-git' // Git and Docker pre-installed
            image 'ubuntu:20.04'
            //args '-v /var/run/docker.sock:/var/run/docker.sock'
        }
    }
    stages {
        stage('Install Java') {
            steps {
                script {
                    // Switch to root user to install packages
                    sh 'sudo apt update'
                    sh 'sudo apt install openjdk-17-jre'
               
                }
            }
        }
        
    }
}
